//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libNOM.test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libNOM.test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Version&quot;:5159,&quot;Platform&quot;:&quot;Win|Final&quot;,&quot;PlayerStateData&quot;:{&quot;UniverseAddress&quot;:{&quot;RealityIndex&quot;:0,&quot;GalacticAddress&quot;:{&quot;VoxelX&quot;:-151,&quot;VoxelY&quot;:8,&quot;VoxelZ&quot;:-1727,&quot;SolarSystemIndex&quot;:76,&quot;PlanetIndex&quot;:4}},&quot;PreviousUniverseAddress&quot;:{&quot;RealityIndex&quot;:0,&quot;GalacticAddress&quot;:{&quot;VoxelX&quot;:0,&quot;VoxelY&quot;:0,&quot;VoxelZ&quot;:0,&quot;SolarSystemIndex&quot;:0,&quot;PlanetIndex&quot;:0}},&quot;HomeRealityIteration&quot;:0,&quot;Inventory&quot;:{&quot;Slots&quot;:[{&quot;Type&quot;:{&quot;InventoryType&quot;:&quot;Technology&quot;},&quot;Id&quot;:&quot;^JET1&quot;,&quot;Amount&quot;:1,&quot;MaxAmount&quot;:100,&quot;DamageFactor&quot;:0.0,&quot;FullyInstalled&quot;:true,&quot;Index&quot;:{&quot;X&quot;:0,&quot;Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string compiler_375_deobfuscated {
            get {
                return ResourceManager.GetString("compiler_375_deobfuscated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;F2P&quot;:5159,&quot;8&gt;q&quot;:&quot;Win|Final&quot;,&quot;6f=&quot;:{&quot;yhJ&quot;:{&quot;Iis&quot;:0,&quot;oZw&quot;:{&quot;dZj&quot;:-151,&quot;IyE&quot;:8,&quot;uXE&quot;:-1727,&quot;vby&quot;:76,&quot;jsv&quot;:4}},&quot;ux@&quot;:{&quot;Iis&quot;:0,&quot;oZw&quot;:{&quot;dZj&quot;:0,&quot;IyE&quot;:0,&quot;uXE&quot;:0,&quot;vby&quot;:0,&quot;jsv&quot;:0}},&quot;QQp&quot;:0,&quot;;l5&quot;:{&quot;:No&quot;:[{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^JET1&quot;,&quot;1o9&quot;:1,&quot;F9q&quot;:100,&quot;eVk&quot;:0.0,&quot;b76&quot;:true,&quot;3ZH&quot;:{&quot;&gt;Qh&quot;:0,&quot;XJ&gt;&quot;:0}},{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^PROTECT&quot;,&quot;1o9&quot;:80,&quot;F9q&quot;:80,&quot;eVk&quot;:0.0,&quot;b76&quot;:true,&quot;3ZH&quot;:{&quot;&gt;Qh&quot;:1,&quot;XJ&gt;&quot;:0}},{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^ENERGY&quot;,&quot;1o9&quot;:100,&quot;F9q&qu....
        /// </summary>
        internal static string compiler_375_obfuscated {
            get {
                return ResourceManager.GetString("compiler_375_obfuscated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Version&quot;:5157,&quot;Platform&quot;:&quot;Win|Final&quot;,&quot;PlayerStateData&quot;:{&quot;UniverseAddress&quot;:{&quot;RealityIndex&quot;:0,&quot;GalacticAddress&quot;:{&quot;VoxelX&quot;:195,&quot;VoxelY&quot;:1,&quot;VoxelZ&quot;:1789,&quot;SolarSystemIndex&quot;:19,&quot;PlanetIndex&quot;:6}},&quot;PreviousUniverseAddress&quot;:{&quot;RealityIndex&quot;:0,&quot;GalacticAddress&quot;:{&quot;VoxelX&quot;:0,&quot;VoxelY&quot;:0,&quot;VoxelZ&quot;:0,&quot;SolarSystemIndex&quot;:0,&quot;PlanetIndex&quot;:0}},&quot;HomeRealityIteration&quot;:0,&quot;Inventory&quot;:{&quot;Slots&quot;:[{&quot;Type&quot;:{&quot;InventoryType&quot;:&quot;Technology&quot;},&quot;Id&quot;:&quot;^JET1&quot;,&quot;Amount&quot;:1,&quot;MaxAmount&quot;:100,&quot;DamageFactor&quot;:0.0,&quot;FullyInstalled&quot;:true,&quot;Index&quot;:{&quot;X&quot;:0,&quot;Y&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string legay_350_deobfuscated {
            get {
                return ResourceManager.GetString("legay_350_deobfuscated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;F2P&quot;:5157,&quot;8&gt;q&quot;:&quot;Win|Final&quot;,&quot;6f=&quot;:{&quot;yhJ&quot;:{&quot;Iis&quot;:0,&quot;oZw&quot;:{&quot;dZj&quot;:195,&quot;IyE&quot;:1,&quot;uXE&quot;:1789,&quot;vby&quot;:19,&quot;jsv&quot;:6}},&quot;ux@&quot;:{&quot;Iis&quot;:0,&quot;oZw&quot;:{&quot;dZj&quot;:0,&quot;IyE&quot;:0,&quot;uXE&quot;:0,&quot;vby&quot;:0,&quot;jsv&quot;:0}},&quot;QQp&quot;:0,&quot;;l5&quot;:{&quot;:No&quot;:[{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^JET1&quot;,&quot;1o9&quot;:1,&quot;F9q&quot;:100,&quot;eVk&quot;:0.0,&quot;b76&quot;:true,&quot;3ZH&quot;:{&quot;&gt;Qh&quot;:0,&quot;XJ&gt;&quot;:0}},{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^PROTECT&quot;,&quot;1o9&quot;:80,&quot;F9q&quot;:80,&quot;eVk&quot;:0.0,&quot;b76&quot;:true,&quot;3ZH&quot;:{&quot;&gt;Qh&quot;:1,&quot;XJ&gt;&quot;:0}},{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^ENERGY&quot;,&quot;1o9&quot;:100,&quot;F9q&quot....
        /// </summary>
        internal static string legay_350_obfuscated {
            get {
                return ResourceManager.GetString("legay_350_obfuscated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Version&quot;:5159,&quot;Platform&quot;:&quot;PS4|Final&quot;,&quot;PlayerStateData&quot;:{&quot;UniverseAddress&quot;:{&quot;RealityIndex&quot;:0,&quot;GalacticAddress&quot;:{&quot;VoxelX&quot;:-1752,&quot;VoxelY&quot;:-3,&quot;VoxelZ&quot;:-381,&quot;SolarSystemIndex&quot;:106,&quot;PlanetIndex&quot;:4}},&quot;PreviousUniverseAddress&quot;:{&quot;RealityIndex&quot;:0,&quot;GalacticAddress&quot;:{&quot;VoxelX&quot;:0,&quot;VoxelY&quot;:0,&quot;VoxelZ&quot;:0,&quot;SolarSystemIndex&quot;:0,&quot;PlanetIndex&quot;:0}},&quot;HomeRealityIteration&quot;:0,&quot;Inventory&quot;:{&quot;Slots&quot;:[{&quot;Type&quot;:{&quot;InventoryType&quot;:&quot;Technology&quot;},&quot;Id&quot;:&quot;^JET1&quot;,&quot;Amount&quot;:1,&quot;MaxAmount&quot;:100,&quot;DamageFactor&quot;:0.0,&quot;FullyInstalled&quot;:true,&quot;Index&quot;:{&quot;X&quot;:0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wizard_362_deobfuscated {
            get {
                return ResourceManager.GetString("wizard_362_deobfuscated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;F2P&quot;:5159,&quot;8&gt;q&quot;:&quot;PS4|Final&quot;,&quot;6f=&quot;:{&quot;yhJ&quot;:{&quot;Iis&quot;:0,&quot;oZw&quot;:{&quot;dZj&quot;:-1752,&quot;IyE&quot;:-3,&quot;uXE&quot;:-381,&quot;vby&quot;:106,&quot;jsv&quot;:4}},&quot;ux@&quot;:{&quot;Iis&quot;:0,&quot;oZw&quot;:{&quot;dZj&quot;:0,&quot;IyE&quot;:0,&quot;uXE&quot;:0,&quot;vby&quot;:0,&quot;jsv&quot;:0}},&quot;QQp&quot;:0,&quot;;l5&quot;:{&quot;:No&quot;:[{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^JET1&quot;,&quot;1o9&quot;:1,&quot;F9q&quot;:100,&quot;eVk&quot;:0.0,&quot;b76&quot;:true,&quot;3ZH&quot;:{&quot;&gt;Qh&quot;:0,&quot;XJ&gt;&quot;:0}},{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^PROTECT&quot;,&quot;1o9&quot;:80,&quot;F9q&quot;:80,&quot;eVk&quot;:0.0,&quot;b76&quot;:true,&quot;3ZH&quot;:{&quot;&gt;Qh&quot;:1,&quot;XJ&gt;&quot;:0}},{&quot;Vn8&quot;:{&quot;elv&quot;:&quot;Technology&quot;},&quot;b2n&quot;:&quot;^ENERGY&quot;,&quot;1o9&quot;:100,&quot;F9q&....
        /// </summary>
        internal static string wizard_362_obfuscated {
            get {
                return ResourceManager.GetString("wizard_362_obfuscated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Version&quot;:5159,&quot;Platform&quot;:&quot;PS4|Final&quot;,&quot;PlayerStateData&quot;:{&quot;UniverseAddress&quot;:{&quot;RealityIndex&quot;:0,&quot;GalacticAddress&quot;:{&quot;VoxelX&quot;:-1752,&quot;VoxelY&quot;:-3,&quot;VoxelZ&quot;:-381,&quot;SolarSystemIndex&quot;:106,&quot;PlanetIndex&quot;:4}},&quot;PreviousUniverseAddress&quot;:{&quot;RealityIndex&quot;:0,&quot;GalacticAddress&quot;:{&quot;VoxelX&quot;:0,&quot;VoxelY&quot;:0,&quot;VoxelZ&quot;:0,&quot;SolarSystemIndex&quot;:0,&quot;PlanetIndex&quot;:0}},&quot;HomeRealityIteration&quot;:0,&quot;Inventory&quot;:{&quot;Slots&quot;:[{&quot;Type&quot;:{&quot;InventoryType&quot;:&quot;Technology&quot;},&quot;Id&quot;:&quot;^JET1&quot;,&quot;Amount&quot;:1,&quot;MaxAmount&quot;:100,&quot;DamageFactor&quot;:0.0,&quot;FullyInstalled&quot;:true,&quot;Index&quot;:{&quot;X&quot;:0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wizard_362_original {
            get {
                return ResourceManager.GetString("wizard_362_original", resourceCulture);
            }
        }
    }
}
