blank_issues_enabled: true
contact_links:
    - name: Ask a Question on Discord
      url: https://discord.gg/3VrAhJVGn7
      about: If you don't have something of the above but a general question, you can ask there to quickly get an answer.
