//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libNOM.map.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libNOM.map.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;libMBIN_version&quot;:&quot;3.72.0.0&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;KLP&quot;,&quot;Value&quot;:&quot;ScreenshotRight&quot;},{&quot;Key&quot;:&quot;fJB&quot;,&quot;Value&quot;:&quot;ScreenshotUp&quot;},{&quot;Key&quot;:&quot;rBG&quot;,&quot;Value&quot;:&quot;PlayerWeaponName&quot;},{&quot;Key&quot;:&quot;14a&quot;,&quot;Value&quot;:&quot;DepthOfFieldAmount&quot;},{&quot;Key&quot;:&quot;uK6&quot;,&quot;Value&quot;:&quot;SectionsData&quot;},{&quot;Key&quot;:&quot;2jw&quot;,&quot;Value&quot;:&quot;DiscovererUID&quot;},{&quot;Key&quot;:&quot;J3C&quot;,&quot;Value&quot;:&quot;DiscovererPlatform&quot;},{&quot;Key&quot;:&quot;OYB&quot;,&quot;Value&quot;:&quot;DiscoveredState&quot;},{&quot;Key&quot;:&quot;ym&gt;&quot;,&quot;Value&quot;:&quot;PlanetaryMappingData&quot;},{&quot;Key&quot;:&quot;TFZ&quot;,&quot;Value&quot;:&quot;SeasonalData&quot;},{&quot;Key&quot;:&quot;:Je&quot;,&quot;Value&quot;:&quot;SecondaryStats&quot;},{&quot;Key&quot;:&quot;OCG&quot;,&quot;Value&quot;:&quot;SunDirSet ....
        /// </summary>
        internal static string Legacy {
            get {
                return ResourceManager.GetString("Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;libMBIN_version&quot;:&quot;3.82.0.2&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;Iis&quot;,&quot;Value&quot;:&quot;RealityIndex&quot;},{&quot;Key&quot;:&quot;dZj&quot;,&quot;Value&quot;:&quot;VoxelX&quot;},{&quot;Key&quot;:&quot;IyE&quot;,&quot;Value&quot;:&quot;VoxelY&quot;},{&quot;Key&quot;:&quot;uXE&quot;,&quot;Value&quot;:&quot;VoxelZ&quot;},{&quot;Key&quot;:&quot;vby&quot;,&quot;Value&quot;:&quot;SolarSystemIndex&quot;},{&quot;Key&quot;:&quot;jsv&quot;,&quot;Value&quot;:&quot;PlanetIndex&quot;},{&quot;Key&quot;:&quot;oZw&quot;,&quot;Value&quot;:&quot;GalacticAddress&quot;},{&quot;Key&quot;:&quot;yhJ&quot;,&quot;Value&quot;:&quot;UniverseAddress&quot;},{&quot;Key&quot;:&quot;ux@&quot;,&quot;Value&quot;:&quot;PreviousUniverseAddress&quot;},{&quot;Key&quot;:&quot;QQp&quot;,&quot;Value&quot;:&quot;HomeRealityIteration&quot;},{&quot;Key&quot;:&quot;elv&quot;,&quot;Value&quot;:&quot;InventoryType&quot;},{&quot;Key&quot;:&quot;Vn8&quot;,&quot;Value&quot;:&quot;Type&quot;},{&quot;Key&quot;:&quot;....
        /// </summary>
        internal static string MBINCompiler {
            get {
                return ResourceManager.GetString("MBINCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mapping.json.
        /// </summary>
        internal static string RELEASE_ASSET {
            get {
                return ResourceManager.GetString("RELEASE_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBINCompiler.
        /// </summary>
        internal static string REPO_NAME {
            get {
                return ResourceManager.GetString("REPO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monkeyman192.
        /// </summary>
        internal static string REPO_OWNER {
            get {
                return ResourceManager.GetString("REPO_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;libMBIN_version&quot;:&quot;3.62.0.0&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;MultiTools&quot;,&quot;Value&quot;:&quot;Multitools&quot;}]}.
        /// </summary>
        internal static string SaveWizard {
            get {
                return ResourceManager.GetString("SaveWizard", resourceCulture);
            }
        }
    }
}
