//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libNOM.map.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libNOM.map.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;libMBIN_version&quot;:&quot;0.13.4&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;5Ta&quot;,&quot;Value&quot;:&quot;AllowFriendBases&quot;},{&quot;Key&quot;:&quot;fDU&quot;,&quot;Value&quot;:&quot;BLANK&quot;},{&quot;Key&quot;:&quot;UpF&quot;,&quot;Value&quot;:&quot;CompletedInteractions&quot;},{&quot;Key&quot;:&quot;?sW&quot;,&quot;Value&quot;:&quot;DepthOfField&quot;},{&quot;Key&quot;:&quot;14a&quot;,&quot;Value&quot;:&quot;DepthOfFieldAmount&quot;},{&quot;Key&quot;:&quot;wKU&quot;,&quot;Value&quot;:&quot;DepthOfFieldStrengthSetting&quot;},{&quot;Key&quot;:&quot;f:D&quot;,&quot;Value&quot;:&quot;DifficultySettings&quot;},{&quot;Key&quot;:&quot;OYB&quot;,&quot;Value&quot;:&quot;DiscoveredState&quot;},{&quot;Key&quot;:&quot;J3C&quot;,&quot;Value&quot;:&quot;DiscovererPlatform&quot;},{&quot;Key&quot;:&quot;2jw&quot;,&quot;Value&quot;:&quot;DiscovererUID&quot;},{&quot;Key&quot;:&quot;UMK&quot;,&quot;Value&quot;:&quot;EyeTracking&quot;},{&quot;Key&quot;:&quot;LDt&quot;,&quot;Value&quot;:&quot;Fl [re....
        /// </summary>
        internal static string Legacy {
            get {
                return ResourceManager.GetString("Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;libMBIN_version&quot;:&quot;5.25.0.1&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;jU1&quot;,&quot;Value&quot;:&quot;x&quot;},{&quot;Key&quot;:&quot;Uoj&quot;,&quot;Value&quot;:&quot;y&quot;},{&quot;Key&quot;:&quot;j22&quot;,&quot;Value&quot;:&quot;z&quot;},{&quot;Key&quot;:&quot;cL6&quot;,&quot;Value&quot;:&quot;BufferAnchors&quot;},{&quot;Key&quot;:&quot;r:j&quot;,&quot;Value&quot;:&quot;GalacticAddresses&quot;},{&quot;Key&quot;:&quot;wMC&quot;,&quot;Value&quot;:&quot;Position&quot;},{&quot;Key&quot;:&quot;8?J&quot;,&quot;Value&quot;:&quot;Data&quot;},{&quot;Key&quot;:&quot;Mes&quot;,&quot;Value&quot;:&quot;Edits&quot;},{&quot;Key&quot;:&quot;eiy&quot;,&quot;Value&quot;:&quot;BufferSizes&quot;},{&quot;Key&quot;:&quot;w0G&quot;,&quot;Value&quot;:&quot;BufferAges&quot;},{&quot;Key&quot;:&quot;deQ&quot;,&quot;Value&quot;:&quot;BufferProtected&quot;},{&quot;Key&quot;:&quot;=o:&quot;,&quot;Value&quot;:&quot;TerrainEditData&quot;},{&quot;Key&quot;:&quot;3@T&quot;,&quot;Value&quot;:&quot;LastBuilding....
        /// </summary>
        internal static string MBINCompiler {
            get {
                return ResourceManager.GetString("MBINCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mapping.json.
        /// </summary>
        internal static string RELEASE_ASSET {
            get {
                return ResourceManager.GetString("RELEASE_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBINCompiler.
        /// </summary>
        internal static string REPO_NAME {
            get {
                return ResourceManager.GetString("REPO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monkeyman192.
        /// </summary>
        internal static string REPO_OWNER {
            get {
                return ResourceManager.GetString("REPO_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;libMBIN_version&quot;:&quot;0.1.0&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;MultiTools&quot;,&quot;Value&quot;:&quot;Multitools&quot;}]}.
        /// </summary>
        internal static string SaveWizard {
            get {
                return ResourceManager.GetString("SaveWizard", resourceCulture);
            }
        }
    }
}
