//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libNOM.map.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libNOM.map.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;libMBIN_version&quot;:&quot;3.72.0.0&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;KLP&quot;,&quot;Value&quot;:&quot;ScreenshotRight&quot;},{&quot;Key&quot;:&quot;fJB&quot;,&quot;Value&quot;:&quot;ScreenshotUp&quot;},{&quot;Key&quot;:&quot;rBG&quot;,&quot;Value&quot;:&quot;PlayerWeaponName&quot;},{&quot;Key&quot;:&quot;14a&quot;,&quot;Value&quot;:&quot;DepthOfFieldAmount&quot;},{&quot;Key&quot;:&quot;uK6&quot;,&quot;Value&quot;:&quot;SectionsData&quot;},{&quot;Key&quot;:&quot;2jw&quot;,&quot;Value&quot;:&quot;DiscovererUID&quot;},{&quot;Key&quot;:&quot;J3C&quot;,&quot;Value&quot;:&quot;DiscovererPlatform&quot;},{&quot;Key&quot;:&quot;OYB&quot;,&quot;Value&quot;:&quot;DiscoveredState&quot;},{&quot;Key&quot;:&quot;ym&gt;&quot;,&quot;Value&quot;:&quot;PlanetaryMappingData&quot;},{&quot;Key&quot;:&quot;TFZ&quot;,&quot;Value&quot;:&quot;SeasonalData&quot;},{&quot;Key&quot;:&quot;:Je&quot;,&quot;Value&quot;:&quot;SecondaryStats&quot;},{&quot;Key&quot;:&quot;OCG&quot;,&quot;Value&quot;:&quot;SunDirSet ... ähnelt.
        /// </summary>
        internal static string Legacy {
            get {
                return ResourceManager.GetString("Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;libMBIN_version&quot;:&quot;3.73.0.1&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;Iis&quot;,&quot;Value&quot;:&quot;RealityIndex&quot;},{&quot;Key&quot;:&quot;dZj&quot;,&quot;Value&quot;:&quot;VoxelX&quot;},{&quot;Key&quot;:&quot;IyE&quot;,&quot;Value&quot;:&quot;VoxelY&quot;},{&quot;Key&quot;:&quot;uXE&quot;,&quot;Value&quot;:&quot;VoxelZ&quot;},{&quot;Key&quot;:&quot;vby&quot;,&quot;Value&quot;:&quot;SolarSystemIndex&quot;},{&quot;Key&quot;:&quot;jsv&quot;,&quot;Value&quot;:&quot;PlanetIndex&quot;},{&quot;Key&quot;:&quot;oZw&quot;,&quot;Value&quot;:&quot;GalacticAddress&quot;},{&quot;Key&quot;:&quot;yhJ&quot;,&quot;Value&quot;:&quot;UniverseAddress&quot;},{&quot;Key&quot;:&quot;ux@&quot;,&quot;Value&quot;:&quot;PreviousUniverseAddress&quot;},{&quot;Key&quot;:&quot;QQp&quot;,&quot;Value&quot;:&quot;HomeRealityIteration&quot;},{&quot;Key&quot;:&quot;elv&quot;,&quot;Value&quot;:&quot;InventoryType&quot;},{&quot;Key&quot;:&quot;Vn8&quot;,&quot;Value&quot;:&quot;Type&quot;},{&quot;Key&quot;:&quot;... ähnelt.
        /// </summary>
        internal static string MBINCompiler {
            get {
                return ResourceManager.GetString("MBINCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;libMBIN_version&quot;:&quot;3.62.0.0&quot;,&quot;Mapping&quot;:[{&quot;Key&quot;:&quot;MultiTools&quot;,&quot;Value&quot;:&quot;Multitools&quot;}]} ähnelt.
        /// </summary>
        internal static string SaveWizard {
            get {
                return ResourceManager.GetString("SaveWizard", resourceCulture);
            }
        }
    }
}
