name: libNOM.map

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Dependencies
        run: dotnet restore
      - name: Unit Test (.NET)
        run: dotnet test libNOM.test --no-restore --configuration Debug --framework net6.0
      - name: Pack
        run: dotnet pack libNOM.map --no-restore --configuration Release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: libNOM.map NuGet Package
          path: libNOM.map/bin/Release/libNOM.map.*nupkg
          if-no-files-found: error
  release:
    name: Release
    runs-on: ubuntu-latest
    # Only if commit was tagged.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: libNOM.map NuGet Package
      - name: Version
        run: echo "dll_version=$(Get-Item -Path .\libNOM.map.*.nupkg | % {Write-Host $_.name.Substring(0, $_.name.LastIndexOf('.')).Substring(11)})" >> $env:GITHUB_ENV
        shell: pwsh
      # Exit if version mismatch.
      - name: Mismatch
        if: ${{ github.ref_name != env.dll_version }}
        run: |
          echo "There is a version mismatch between git tag and dll version!"
          exit 1
      # Checkout again to access the changelog.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/.github/changelogs/${{ github.ref_name }}.md
          files: libNOM.map.*nupkg
