name: libNOM.map

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Dependencies
        run: dotnet restore
      - name: Unit Test (.NET)
        run: dotnet test libNOM.test --no-restore --configuration Debug --framework net6.0
      - name: Pack
        run: dotnet pack libNOM.map --no-restore --configuration Release
      - name: Version
        run: echo "dll_version=$((Get-Command libNOM.map\bin\Release\net6.0\libNOM.map.dll).FileVersionInfo.ProductVersion)" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Upload (NuGet Package)
        uses: actions/upload-artifact@v3
        with:
          name: libNOM.map NuGet Package (nupkg)
          path: libNOM.map/bin/Release/libNOM.map.*.nupkg
          if-no-files-found: error
      - name: Upload (Symbol Package)
        uses: actions/upload-artifact@v3
        with:
          name: libNOM.map Symbol Package (snupkg)
          path: libNOM.map/bin/Release/libNOM.map.*.snupkg
          if-no-files-found: error
  release:
    name: Release
    runs-on: ubuntu-latest
    # Only if commit was tagged.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    steps:
      # Checkout to access the changelog.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: libNOM.map
      # Exit if version mismatch.
      - name: Mismatch
        if: ${{ github.ref_name != env.dll_version }}
        run: |
          echo "There is a version mismatch between git tag and dll version!"
          exit 1
      - name: Create
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/.github/changelogs/${{ github.ref_name }}.md
          files: |
            net6.0/libNOM.map.dll
            net6.0/publish/libNOM.map.zip
            libNOM.map.*.nupkg
