name: libNOM.map

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  create:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        # November, 2026 / May, 2026
        framework: [{dotnet: 'net8.0', version: '9.0.x'}, {dotnet: 'net9.0', version: '9.0.x'}] # set up 9.0 for all as there is an error when executing the tests on 8.0 otherwise (macos, ubuntu)
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.framework.version }}
          dotnet-quality: ga
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Unit Test
        run: dotnet test libNOM.test --configuration Debug --framework ${{ matrix.framework.dotnet }} --settings test.runsettings
      - name: Upload Coverage
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ./TestResults/**/*.cobertura.xml
          format: cobertura
  build:
    name: Build
    strategy:
      matrix:
        framework: ['9.0.x'] # must match project file
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.framework }}
          dotnet-quality: ga
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Pack
        run: dotnet pack libNOM.map --configuration Release
      - name: Upload (NuGet)
        uses: actions/upload-artifact@v4
        with:
          name: NuGet
          path: ./libNOM.map/bin/Release/libNOM.map.*nupkg
          if-no-files-found: error
      - name: Upload (Release)
        if: ${{ startsWith(github.ref, 'refs/tags/') }} # only if tagged
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: ./.github/changelogs/${{ github.ref_name }}.md
          if-no-files-found: error
  release:
    name: Release
    if: ${{ startsWith(github.ref, 'refs/tags/') }} # only if tagged
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Download
        uses: actions/download-artifact@v5
      - name: Version
        run: echo "nupkg_version=$((((Get-Item -Path ./NuGet/libNOM.map.*.nupkg).Name -split '\.',3)[2] -split '\.',-2)[0])" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Mismatch
        if: ${{ github.ref_name != env.nupkg_version }}
        run: |
          echo "There is a version mismatch between git tag (${{ github.ref_name }}) and nupkg version (${{ env.nupkg_version }})!"
          exit 1
      - name: Create
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./Release/${{ github.ref_name }}.md
          files: ./NuGet/libNOM.map.*nupkg
      - name: Publish
        run: dotnet nuget push ./NuGet/libNOM.map.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
