name: libNOM.map

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  create:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        # November, 2024 / May, 2024 / November, 2026
        framwork: [net6.0, net7.0, net8.0]
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          dotnet-quality: ga
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Unit Test
        run: dotnet test libNOM.test --configuration Debug --framework ${{ matrix.framwork }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          dotnet-quality: ga
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Pack
        run: dotnet pack libNOM.map --configuration Release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: NuGet
          path: |
            ./.github/changelogs/
            ./libNOM.map/bin/Release/libNOM.map.*nupkg
          if-no-files-found: error
  release:
    name: Release
    runs-on: ubuntu-latest
    # Only if commit was tagged.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [test, build]
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: NuGet
      - name: Version
        run: echo "nupkg_version=$((((Get-Item -Path ./libNOM.map/bin/Release/libNOM.map.*.nupkg).Name -split '\.',3)[2] -split '\.',-2)[0])" >> $env:GITHUB_ENV
        shell: pwsh
      # Exit if version mismatch.
      - name: Mismatch
        if: ${{ github.ref_name != env.nupkg_version }}
        run: |
          echo "There is a version mismatch between git tag (${{ github.ref_name }}) and nupkg version (${{ env.nupkg_version }})!"
          exit 1
      - name: Create
        uses: softprops/action-gh-release@d99959edae48b5ffffd7b00da66dcdb0a33a52ee
        with:
          body_path: ./.github/changelogs/${{ github.ref_name }}.md
          files: ./libNOM.map/bin/Release/libNOM.map.*nupkg
      - name: Publish
        run: dotnet nuget push ./libNOM.map/bin/Release/libNOM.map.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
