name: libNOM.map

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Dependency
        run: dotnet restore
      - name: Unit Test
        run: dotnet test libNOM.test --no-restore
      - name: Build
        run: dotnet publish libNOM.map -c Release --no-restore
      - name: NuGet
        run: dotnet pack libNOM.map -c Release --no-restore
      - name: Archive
        uses: thedoctor0/zip-release@0.6.1
        with:
          filename: 'libNOM.map.zip'
          directory: 'libNOM.map/bin/Release/net6.0/publish'
          exclusions: '*.json *.pdb'
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: libNOM.map
          path: |
            libNOM.map/bin/Release/net6.0/libNOM.map.dll
            libNOM.map/bin/Release/net6.0/publish/libNOM.map.zip
            libNOM.map/bin/Release/libNOM.map.*.nupkg
  release:
    name: Release
    runs-on: ubuntu-latest
    # Only if commit was tagged.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: libNOM.map
      - name: Version
        run: echo "dll_version=$((Get-Command .\libNOM.map\bin\Release\net6.0\libNOM.map.dll).FileVersionInfo.ProductVersion)" >> $env:GITHUB_ENV
        shell: pwsh
      # Exit if version mismatch.
      - name: Mismatch
        if: ${{ github.ref_name != env.dll_version }}
        run: |
          echo "There is a version mismatch between git tag and dll version!"
          exit 1
      # Checkout to access the changelog.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/.github/changelogs/${{ github.ref_name }}.md
          files: |
            net6.0/libNOM.map.dll
            net6.0/publish/publish/libNOM.map.zip
            libNOM.map.*.nupkg
